services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.5
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  python-app:
    build: ./app
    volumes:
      - ./app:/app
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - kafka
    command: tail -f /dev/null

  spark:
    image: bitnami/spark:3.4.2
    user: root
    environment:
      - SPARK_MODE=client
      - HOME=/tmp
    volumes:
      - ./app/spark_streaming:/app/spark_streaming
    depends_on:
      - kafka
    command: tail -f /dev/null


